#!/usr/bin/env bash
# Install nginx on your web-01
# Configure your Nginx server so that /redirect_me is redirecting to another
# page
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
