#!/usr/bin/env bash
# Setting up hostname in nginx headers
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install nginx -y
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
