#!/usr/bin/env bash
# Setting up hostname in nginx headers
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install nginx -y
sudo sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx start
