#!/usr/bin/env bash
#output bad luck and good luck for 4th and 8th iteration resp.

i=1
while [ $i -le 10 ]
do
    if ((i == 4))
    then
	echo "bad luck"
    elif ((i == 8))
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((i++))
done
